### ISSUE TITLE
attempt to write a readonly database, crashes on android 5.0v devices while using SqlCipher

### ISSUE THREAD

**Issue by praveenb** [sqlcipher/sqlcipher#120]
Im getting following log on app crash android 5.0v devices

Caused by: net.sqlcipher.database.SQLiteException: attempt to write a readonly database
at net.sqlcipher.database.SQLiteDatabase.native_setLocale(Native Method)
at net.sqlcipher.database.SQLiteDatabase.setLocale(SQLiteDatabase.java:2096)
at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:1962)
at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:881)
at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:913)
at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:132)
at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:99)
at PackageName.DBHelperCipher.<init>(DBHelperCipher.java:93)
at PackageName.ProcessDBCipherInitTask.doInBackground(ProcessDBCipherInitTask.java:20)
at PackageName.ProcessDBCipherInitTask.doInBackground(ProcessDBCipherInitTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)

I've submitted a question on StackOverflow, http://stackoverflow.com/q/29988933/341443.
Can you please help on this.

Thank you.

**Comment by praveenb** [comment]
just reposted the same issue, in related github source... https://github.com/sqlcipher/android-database-sqlcipher/issues/161

**Comment by developernotes** [comment]
I am closing this issue as it is duplicated in the [sqlcipher/android-database-sqlcipher](https://github.com/sqlcipher/android-database-sqlcipher) project as issue [#161](https://github.com/sqlcipher/android-database-sqlcipher/issues/161).
