### ISSUE TITLE
Can't find SQLiteDatabase.mNativeHandle using HUAWEI Mate 8

### ISSUE THREAD

**Issue by tiborobit** [sqlcipher/sqlcipher#152]
I'm facing this error on our application is there an missing .so file in our SQLCipher.. we manage to implement it to MIPS devices it's working with Samsung galaxy Note 5. We are using SQLCipher Version 4.3.5. Is it compatible to that chipset? Thanks.

(1:37:00 PM) 02-01 13:04:58.286: E/Database(3178): Can't find SQLiteDatabase.mNativeHandle
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception 'java.lang.NoSuchFieldError' thrown in java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String):-2
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]     in call to FindClass
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]     from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String)
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65] "Thread-2459" prio=5 tid=18 Runnable
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12c06ee0 self=0x55a659ac10
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   | sysTid=3202 nice=0 cgrp=default sched=0/0 handle=0x55a65a5510
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   | state=R schedstat=( 17883168 2700000 77  utm=1 stm=0 core=1 HZ=100
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   | stack=0x7f9e4eb000-0x7f9e4ed000 stackSize=1036KB
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   native: #00 pc 00003a34  /system/lib64/libbacktrace_libc++.so (Backtrace::Unwind(unsigned long, ucontext*)+28)
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   native: #01 pc 00000027  ???
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   at java.lang.Runtime.nativeLoad(Native method)
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   at java.lang.Runtime.doLoad(Runtime.java:440)
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   - locked <0x112de2d5> (a java.lang.Runtime)
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   at java.lang.Runtime.loadLibrary(Runtime.java:381)
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   at java.lang.System.loadLibrary(System.java:997)
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:120)
02-01 13:04:58.316: A/art(3178): art/runtime/check_jni.cc:65]   at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:113)

**Comment by developernotes** [comment]
Hello @tiborobit 

We do not provide native library builds for the MIPS architecture, is that where you received this error?  Was it on a specific device, or an emulator?

**Comment by tiborobit** [comment]
It's the specific device.. huawei mate 8. we're using this libs 
![sqlcipherlib](https://cloud.githubusercontent.com/assets/9128671/12744368/d3482e40-c9ce-11e5-8988-97d04cd1f979.PNG)  we managed to work the library using  Samsung Galaxy Node Edge Actual Device..

**Comment by developernotes** [comment]
Hello @tiborobit 

What is contained within the `arm64-v8a`, and `x86_64` folders?  We do not provide binaries for those platforms.  What value does the Huawei Mate 8 report when you run the following?
```
System.getProperty("os.arch");
```

**Comment by TNT-Boom** [comment]
Hello, I met a same problem on Vivo Y22 and Hongmi 1. Have you solved this probblem? Could you help me?

**Comment by sjlombardo** [comment]
closing due to inactivity.
