### ISSUE TITLE
"file is encrypted or is not a database" after updating sqlcipher to 3.5.7

### ISSUE THREAD

**Issue by nirmalspeed** [sqlcipher/sqlcipher#218]
### Expected Behavior
`dbHelper.getWritableDatabase(encryptionKey)` should return the existing database.
### Actual Behavior
```Database: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
  net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
      at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
      at net.sqlcipher.database.SQLiteCompiledSql.compile(SourceFile:91)
      at net.sqlcipher.database.SQLiteCompiledSql.<init>(SourceFile:64)
      at net.sqlcipher.database.SQLiteProgram.<init>(SourceFile:89)
      at net.sqlcipher.database.SQLiteQuery.<init>(SourceFile:48)
      at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SourceFile:60)
      at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SourceFile:1867)
      at net.sqlcipher.database.SQLiteDatabase.rawQuery(SourceFile:1785)
      at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SourceFile:2486)
      at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SourceFile:2415)
      at net.sqlcipher.database.SQLiteDatabase.openDatabase(SourceFile:1149)
      at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SourceFile:1212)
      at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SourceFile:162)
      at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SourceFile:129)
      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
      at android.app.ActivityThread.access$1300(ActivityThread.java:141)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loop(Looper.java:137)
      at android.app.ActivityThread.main(ActivityThread.java:5103)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:525)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
      at dalvik.system.NativeStart.main(Native Method)
```

### Steps to Reproduce
```this.ctx = context;
this.encryptionKey = Base64.encodeToString(encryptionKey.getBytes(), Base64.DEFAULT);
this.dbHelper = new DatabaseHelper(MyApplication.getAppContext());
SQLiteDatabase.loadLibs(this.ctx);
this.database = dbHelper.getWritableDatabase(encryptionKey); //crashes here
```

SQLCipher version: 
Unsure of actual old library version but, `PRAGMA cipher_version` for old db file says 3.4.1? 
sqlcipher.jar that was in our old app version is from 2013. 
Crash happening when updating app from old version to new version running sqlcipher v3.5.7

**Comment by developernotes** [comment]
Hi @nirmalspeed 

>Unsure of actual old library version but, PRAGMA cipher_version for old db file says 3.4.1?

We actually need the version of the _old_ SQLCipher library used to originally create the database file. When you execute `PRAGMA cipher_version;`, it is returning a compiled string value from the library itself, not the database file. Can you run `PRAGMA cipher_version;` when using the old SQLCipher database library, before you upgraded to 3.5.7 and let us know your results?

**Comment by nirmalspeed** [comment]
Thanks for that comment? I didn't realize that the check wasn't for the db itself. the sqlcipher was probably a 2.X version and I ended up fixing the issue via migration like so: 
```
SQLiteDatabaseHook hook = new SQLiteDatabaseHook() {
				public void preKey(SQLiteDatabase database) {}
				public void postKey(SQLiteDatabase database) {
					String value = singleValueFromQuery(database, "PRAGMA cipher_migrate");
				}
			};
String version = MyApplication.getAppContext().getDatabasePath(DatabaseHelper.DB_NAME).getPath();
File dbPathFile = new File(version);
database = SQLiteDatabase.openOrCreateDatabase(dbPathFile,
		encryptionKey, null, hook);
```

Now, is there a way to check if the migration is required before doing it so it doesn't have to run that migration every time?

Also, are there any differences/side affects to know about when using the `openOrCreateDatabase` instead of `getWritableDatabase`?

**Comment by developernotes** [comment]
Hi @nirmalspeed 

We are happy to hear everything is working properly for you now. We recommend that you track whether you have upgraded the database file format itself externally to remove the need to attempt the migration process repeatedly. Repeated calls to perform a `PRAGMA cipher_migrate;` will only slow down your execution as it will attempt to determine whether a file format migration is necessary.

>Also, are there any differences/side affects to know about when using the openOrCreateDatabase instead of getWritableDatabase?

Not specifically, internally, the `SQLiteOpenHelper` utilizes `openOrCreateDatabase`. The `SQLiteOpenHelper` simply provides a series of convenient features for developers, such as a mechanism to perform database migration.
