### ISSUE TITLE
Is getEncryptedWritableDb a time-consuming operation

### ISSUE THREAD

**Issue by gongzelong0718** [sqlcipher/sqlcipher#279]
We should not call it on the main thread when an android app is launched, right?

"main" prio=5 tid=1 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x4208c710 self=0x42076610
| sysTid=23012 nice=0 sched=0/0 cgrp=apps handle=1074516220
| state=R schedstat=( 3177844040 986116949 3487 ) utm=243 stm=74 core=2
#00 pc 0000e2a0 /system/lib/libc.so
#01 pc 0000dc27 /system/lib/libc.so (free+10)
#02 pc 0010b560 /data/app-lib/com.meituan.retail.c.android-1/libsqlcipher.so (EVP_MD_CTX_reset+188)
at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1867)
at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1785)
at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2486)
at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2415)
at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1149)
at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1212)
at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)
at org.greenrobot.greendao.database.DatabaseOpenHelper.getEncryptedWritableDb(DatabaseOpenHelper.java:134)

**Comment by developernotes** [comment]
Hello @gongzelong0718 

This exception appears from the greenDAO library, however in general you may want to move time sensitive operations such as database operations off the UI thread to prevent delays.
