### ISSUE TITLE
segmentation fault on exit

### ISSUE THREAD

**Issue by MatthewHannigan** [sqlcipher/sqlcipher#293]
### Expected Behavior
exits with no error
### Actual Behavior
exits with segmentation fault
```
~ $ sqlcipher 
SQLCipher version 3.25.2 2018-09-25 19:08:10
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> ^DSegmentation fault: 11
```
### Steps to Reproduce
start and exit (with ^d)
SQLCipher version:
3.25.2

**Comment by MatthewHannigan** [comment]
Installed with homebrew:
```~ $  brew install sqlcipher
==> Installing dependencies for sqlcipher: openssl
==> Installing sqlcipher dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2q.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssl-1.0.2q.high_sierra.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

openssl is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.

If you need to have openssl first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl/include"

For pkg-config to find openssl you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2q: 1,794 files, 12.1MB
==> Installing sqlcipher
==> Downloading https://homebrew.bintray.com/bottles/sqlcipher-4.0.0.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring sqlcipher-4.0.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/sqlcipher/4.0.0: 12 files, 2.8MB
==> Caveats
==> openssl
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

openssl is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.

If you need to have openssl first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl/include"

For pkg-config to find openssl you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"

```

**Comment by sjlombardo** [comment]
Hello @MatthewHannigan - thanks so much for the report! I've reproduced this issue - we'll get a fix out for this in the next release. I'll leave this ticket open until then.

**Comment by coleifer** [comment]
Came here to report the same thing. Looking forward to a fix.

**Comment by coleifer** [comment]
Backtrace, for what its worth:

```
Program received signal SIGSEGV, Segmentation fault.
__strcspn_sse42 (s=0x0, a=<optimized out>)
    at ../sysdeps/x86_64/multiarch/strcspn-c.c:162
162	../sysdeps/x86_64/multiarch/strcspn-c.c: No such file or directory.
(gdb) bt full
#0  __strcspn_sse42 (s=0x0, a=<optimized out>)
    at ../sysdeps/x86_64/multiarch/strcspn-c.c:162
        aligned = 0x0
        offset = 0
#1  0x00007ffff7ae23e6 in patternCompare () from /usr/local/lib/libsqlcipher.so.0
No symbol table info available.
#2  0x00005555555745ae in process_input ()
No symbol table info available.
#3  0x000055555555a924 in main ()
No symbol table info available.
```

**Comment by coleifer** [comment]
I think the problem may be here, you're not testing for zResult being NULL:

```diff
--- sqlite/src/shell.c.in	2018-12-03 09:51:24.115577714 -0600
+++ sqlcipher/src/shell.c.in	2018-12-05 09:23:03.867413591 -0600
@@ -633,6 +633,15 @@
 #else
     free(zPrior);
     zResult = shell_readline(zPrompt);
+/* BEGIN SQLCIPHER */
+#ifdef SQLITE_HAS_CODEC
+    /* Simplistic filtering of input lines to prevent PRAGKA key and 
+       PRAGMA rekey statements from being stored in readline history. 
+       Note that this will only prevent single line statements, but that
+       will be sufficient for common cases. */ 
+    if(sqlite3_strlike("%pragma%key%=%", zResult, 0)==0) return zResult;
+#endif
+/* END SQLCIPHER */
     if( zResult && *zResult ) shell_add_history(zResult);
 #endif
   }
```

**Comment by sjlombardo** [comment]
@coleifer agreed, that is the issue. I fixed it yesterday on the prerelease branch, but forgot to push to github.

**Comment by coleifer** [comment]
Thanks, looking forward to seeing that merged. Thank you for the hard work and the latest update to 3.25.2.

**Comment by coleifer** [comment]
@sjlombardo -- do you know when the patch will be merged into master?

**Comment by sjlombardo** [comment]
Hello @coleifer - the change is pushed up on the prerelease branch right now for testing and use. Typically we wait until a full release is finalized before merging into master. There are a few other items we have planned on our to-do list before the net release. Can you use prerelease until then?

**Comment by coleifer** [comment]
@sjlombardo -- for sure, I was just curious what the release process was like and whether you had a timeline for merging the fix. It's not causing any data-loss or issues, and I only ever use the CLI for quick prototyping anyways, so it's no problem. Thanks again to you and your team for the 4.0 release.

**Comment by coleifer** [comment]
With the release of 4.0.1 (which bumps sqlite to 3.26.0, props to you guys for the quick security update), this issue can be closed.

**Comment by sjlombardo** [comment]
Thanks for confirming and taking the time to report the issue. I'll close this now.
