### ISSUE TITLE
Error inserting <redacted values> into table

### ISSUE THREAD

**Issue by AAGSICON** [sqlcipher/sqlcipher#308]
### Steps to Reproduce
1. Create database 
2. Insert values
3. Delete Databse
4. Try to create new Database with same name and try to insert values.

SQLCipher version: 'net.zetetic:android-database-sqlcipher:4.0.1@aar'

2019-03-04 16:03:24.294 7852-8427/? E/Database: Error inserting <redacted values> into discovery_results
    net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database
        at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
        at net.sqlcipher.database.SQLiteStatement.execute(SQLiteStatement.java:58)
        at net.sqlcipher.database.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:2161)
        at net.sqlcipher.database.SQLiteDatabase.insert(SQLiteDatabase.java:2017)
*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hi @AAGSICON 

Are you closing the database before you delete the file? Are you able to consistently reproduce the issue? We would be happy to look into this further, would you mind creating a small test within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) that models the behavior you are experiencing so we can investigate?
