### ISSUE TITLE
SQLiteException

### ISSUE THREAD

**Issue by deepakunnikrishnanfi** [sqlcipher/sqlcipher#486]
### Expected Behavior
No crash

### Actual Behavior
Getting a crash.

Crash log: 
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
       at java.util.concurrent.FutureTask.run(FutureTask.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

Caused by net.sqlcipher.database.SQLiteException: database is locked: , while compiling: select count(*) from sqlite_master;
       at net.sqlcipher.database.SQLiteCompiledSql.native_compile(SQLiteCompiledSql.java)
       at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:89)
       at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
       at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:91)
       at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
       at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
       at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2016)
       at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1902)
       at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2669)
       at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2599)
       at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1247)
       at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1322)
       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:166)
       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:135)
       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:131)

### Steps to Reproduce
We are unable to find when this occured. But received multiple crash logs.

SQLCipher version:
android-database-sqlcipher:4.5.3

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
This was cross posted to the [discussion site](https://discuss.zetetic.net/t/sqliteexception-database-is-locked-while-compiling-select-count-from-sqlite-master/6107/2). Since this is not related to sqlcipher core (this project) I am closing this ticket in favor of discussion on the linked post.
